### ISSUE TITLE
'RuntimeError: Event loop is closed' when running under Windows

### ISSUE THREAD

**Issue by heckler** [nedbat/dinghy#9]
When running dinghy under windows I'm getting an 'Event loop is closed' error from the asyncio lib, even though the output file is created without issues.

The exact same command runs fine under Ubuntu, without exceptions - same repository, github token, dinghy version; error only happens on windows.

- Windows version:  Windows 10 20H2 19042.1766, 64b
- Python version: 3.9.1  (64b)
- Dinghy version: 0.12.0

**Note:** the digest.html file was generated fine, so the exception thrown might be a minor issue related to resource cleanup.

## Error log

```text
C:\Users\heckler>python3 -m dinghy https://github.com/heckler/home-assistant-config
Wrote digest: digest.html
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000221711D58B0>
Traceback (most recent call last):
  File "C:\Users\heckler\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\heckler\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\heckler\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\heckler\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000221711D58B0>
Traceback (most recent call last):
  File "C:\Users\heckler\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\heckler\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\heckler\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\heckler\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by nedbat** [comment]
Hmm, very odd. Can you try it on a newer version of 3.9? or on 3.10?

**Comment by heckler** [comment]
>  Can you try it on a newer version of 3.9? or on 3.10?

Sure!  Tested on 3.10.5 amd64 just now.   Otherwise, same environment as before. This time I had a yaml config pointing to GHE (earlier test was github.com), but as before, the digest was written just fine, so this exception happens when the app is terminating.

```text
$ python --version
Python 3.10.5

$ python -m dinghy
Wrote digest: group_digest.html
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000132857049D0>
Traceback (most recent call last):
  File "C:\Users\heckler\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\heckler\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\heckler\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\heckler\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by nedbat** [comment]
This seems to be a [known problem](https://github.com/python/cpython/issues/83413) that is [fixed in 3.10.6](https://github.com/python/cpython/pull/92904).

**Comment by carltongibson** [comment]
Confirming that it doesn’t reproduce with Python 3.10.6. 

Adding something like…

```
if sys.version_info < (3, 10, 6) and sys.platform.startswith('win'):
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```

… should silence it on earlier versions.

**Comment by nedbat** [comment]
Thanks, I've added that in c64c247.  @heckler Can you try it?

**Comment by nedbat** [comment]
I've released this as 0.13.1.

**Comment by graingert** [comment]
This issue still happens on the SelectorEventLoop (enable ResourceWarnins) , it's just hidden by default

**Comment by heckler** [comment]
> Thanks, I've added that in [c64c247](https://github.com/nedbat/dinghy/commit/c64c247c92a959b20b0ef35dc4941fd124d15bbd). @heckler Can you try it?

Sure thing!

- Tested without the fix, under 3.10.5 (warning, as expected) and 3.10.6 (no issues observed)
- Tested [c64c247] under both 3.10.5 and 3.10.6, no warnings or issues on either

This is as good as closed.  Thank you!  :)

**Comment by graingert** [comment]
```
python -Werror -m dinghy https://github.com/Me/MyProject
error: dinghy error: Unauthorized. You need to create a GITHUB_TOKEN environment variable.
Exception ignored in: <function _SelectorTransport.__del__ at 0x7f264ea12320>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 701, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
ResourceWarning: unclosed transport <_SelectorSocketTransport fd=7>
Exception ignored in: <function _SelectorTransport.__del__ at 0x7f264ea12320>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 701, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
ResourceWarning: unclosed transport <_SelectorSocketTransport fd=6>
Exception ignored in: <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.50.135', 49202), raddr=('140.82.121.6', 443)>
ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.50.135', 49202), raddr=('140.82.121.6', 443)>
Exception ignored in: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.50.135', 49204), raddr=('140.82.121.6', 443)>
ResourceWarning: unclosed <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.50.135', 49204), raddr=('140.82.121.6', 443)>
```

**Comment by graingert** [comment]
you can just ignore the runtime error rather than switching over to the SelectorEventLoop:

```python
import sys

old_hook = sys.unraisablehook

def unraisablehook(unraisable, /):
    if unraisable.err_msg == "RuntimeError: Event loop is closed":
        return
    return old_hook(unraisable)
```

(more people should use the ProactorEventLoop!)

**Comment by nedbat** [comment]
@graingert I appreciate the advice, but am more comfortable with switching the loop than suppressing the message, and this will all be unneeded eventually anyway. Thanks all for your help!

**Comment by carltongibson** [comment]
@graingert That's a good comment! 👀 

This is dark arts. Is it documented? Might be worth a blog post... 

Interesting.

**Comment by graingert** [comment]
> @graingert That's a good comment! 👀
> 
> This is dark arts. Is it documented? Might be worth a blog post...
> 
> Interesting.

https://vstinner.github.io/sys-unraisablehook-python38.html
